import { Router, Response } from 'express';
import { query } from '../../config/database';
import { AuthRequest } from '../../middleware/auth';
import { asyncHandler } from '../../middleware/asyncHandler';
import logger from '../../utils/logger';
import { emitToGroup } from '../../socket';
import { commentOnResponses, AiPersonality } from '../../services/aiService';
import { validateUuidParams } from '../../middleware/validateParams';
import { CHALLENGE_SELECT, processSkipsForChallenge } from './shared';

const router = Router();

// ── GET /api/challenges/pending — All active, unresponded challenges across all user's groups ──
router.get('/pending', asyncHandler(async (req: AuthRequest, res: Response) => {
  const result = await query(
    `SELECT c.id, c.group_id, g.name as group_name, g.icon as group_emoji, g.ai_personality,
            c.type, c.prompt_text as prompt, c.options_json as options,
            c.expires_at, c.countdown_seconds, c.triggered_by, c.is_auto_generated,
            (SELECT COUNT(*)::int FROM group_members WHERE group_id = c.group_id) as total_members,
            (SELECT COUNT(*)::int FROM challenge_responses WHERE challenge_id = c.id AND response_type != 'skip') as responded_count
     FROM challenges c
     JOIN groups g ON g.id = c.group_id
     JOIN group_members gm ON gm.group_id = c.group_id AND gm.user_id = $1
     WHERE c.status = 'active'
       AND c.expires_at > NOW()
       AND NOT EXISTS (
         SELECT 1 FROM challenge_responses cr
         WHERE cr.challenge_id = c.id AND cr.user_id = $1
       )
     ORDER BY c.expires_at ASC`,
    [req.userId]
  );

  // Parse options and format response
  const challenges = result.rows.map((row: any) => {
    let options = row.options;
    if (options && typeof options === 'string') {
      try { options = JSON.parse(options); } catch { /* keep as-is */ }
    }
    return {
      id: row.id,
      groupId: row.group_id,
      groupName: row.group_name,
      groupEmoji: row.group_emoji,
      type: row.type,
      prompt: row.prompt,
      options,
      expiresAt: row.expires_at,
      countdownSeconds: row.countdown_seconds,
      totalMembers: row.total_members,
      respondedCount: row.responded_count,
      triggeredBy: row.triggered_by,
      isAutoGenerated: row.is_auto_generated || false,
    };
  });

  res.json(challenges);
}));

// ── GET active challenge ──
router.get('/groups/:groupId/challenges/active', validateUuidParams('groupId'), asyncHandler(async (req: AuthRequest, res: Response) => {
  const groupId = req.params.groupId as string;

  const membership = await query(
    `SELECT * FROM group_members WHERE group_id = $1 AND user_id = $2`,
    [groupId, req.userId]
  );
  if (membership.rows.length === 0) {
    res.status(403).json({ error: 'Not a member of this group' });
    return;
  }

  // Auto-expire and process skips
  const expired = await query(
    `SELECT id FROM challenges
     WHERE group_id = $1 AND status = 'active' AND expires_at < NOW()`,
    [groupId]
  );
  for (const e of expired.rows) {
    await processSkipsForChallenge(e.id, groupId);
  }
  await query(
    `UPDATE challenges SET status = 'expired'
     WHERE group_id = $1 AND status = 'active' AND expires_at < NOW()`,
    [groupId]
  );

  // Return active challenges OR completed/expired ones still within their countdown window
  const result = await query(
    `SELECT ${CHALLENGE_SELECT} FROM challenges
     WHERE group_id = $1
       AND (status = 'active' OR (status IN ('completed', 'expired') AND expires_at > NOW()))
     ORDER BY created_at DESC LIMIT 1`,
    [groupId]
  );

  if (result.rows.length === 0) {
    res.json(null);
    return;
  }

  const challenge = result.rows[0];
  // Parse options_json string into an actual array for the client
  if (challenge.options && typeof challenge.options === 'string') {
    try { challenge.options = JSON.parse(challenge.options); } catch { /* keep as-is */ }
  }

  const userResponse = await query(
    `SELECT id FROM challenge_responses WHERE challenge_id = $1 AND user_id = $2`,
    [challenge.id, req.userId]
  );

  res.json({
    ...challenge,
    user_has_responded: userResponse.rows.length > 0,
  });
}));

// ── GET responses (can't peek until you play) ──
router.get('/:id/responses', validateUuidParams('id'), asyncHandler(async (req: AuthRequest, res: Response) => {
  const id = req.params.id as string;

  const userResponse = await query(
    `SELECT id FROM challenge_responses WHERE challenge_id = $1 AND user_id = $2`,
    [id, req.userId]
  );
  if (userResponse.rows.length === 0) {
    res.status(403).json({ error: "Can't peek until you play! Respond first." });
    return;
  }

  const responses = await query(
    `SELECT cr.*, COALESCE(u.display_name, u.phone_number) AS display_name, u.avatar_url
     FROM challenge_responses cr
     JOIN users u ON u.id = cr.user_id
     WHERE cr.challenge_id = $1
     ORDER BY cr.responded_at`,
    [id]
  );

  // Fetch reactions for all responses in this challenge
  const responseIds = responses.rows.map((r: any) => r.id);
  let reactionsMap: Record<string, { emoji: string; count: number; users: string[] }[]> = {};

  if (responseIds.length > 0) {
    const reactions = await query(
      `SELECT r.response_id, r.emoji, COUNT(*) as count,
              ARRAY_AGG(COALESCE(u.display_name, u.phone_number)) as user_names
       FROM reactions r
       JOIN users u ON u.id = r.user_id
       WHERE r.response_id = ANY($1)
       GROUP BY r.response_id, r.emoji
       ORDER BY count DESC`,
      [responseIds]
    );

    for (const row of reactions.rows) {
      if (!reactionsMap[row.response_id]) {
        reactionsMap[row.response_id] = [];
      }
      reactionsMap[row.response_id].push({
        emoji: row.emoji,
        count: parseInt(row.count),
        users: row.user_names,
      });
    }
  }

  const responsesWithReactions = responses.rows.map((r: any) => ({
    ...r,
    reactions: reactionsMap[r.id] || [],
  }));

  res.json(responsesWithReactions);
}));

// ── GET /api/challenges/:id/reveal — Full reveal data for completed challenge ──
router.get('/:id/reveal', validateUuidParams('id'), asyncHandler(async (req: AuthRequest, res: Response) => {
  const id = req.params.id as string;

  // Verify challenge exists
  const challengeResult = await query(
    `SELECT c.*, g.name as group_name, g.icon as group_emoji, g.ai_personality
     FROM challenges c
     JOIN groups g ON g.id = c.group_id
     WHERE c.id = $1`,
    [id]
  );
  if (challengeResult.rows.length === 0) {
    res.status(404).json({ error: 'Challenge not found' });
    return;
  }
  const c = challengeResult.rows[0];

  // Verify user is a group member
  const membership = await query(
    `SELECT * FROM group_members WHERE group_id = $1 AND user_id = $2`,
    [c.group_id, req.userId]
  );
  if (membership.rows.length === 0) {
    res.status(403).json({ error: 'Not a member of this group' });
    return;
  }

  // Can't peek gate — user must have responded
  const userResponse = await query(
    `SELECT id FROM challenge_responses WHERE challenge_id = $1 AND user_id = $2`,
    [id, req.userId]
  );
  if (userResponse.rows.length === 0) {
    res.status(403).json({ error: "Can't peek until you play! Respond first." });
    return;
  }

  // Fetch all non-skip responses with user info
  const responses = await query(
    `SELECT cr.*, COALESCE(u.display_name, u.phone_number) AS display_name, u.avatar_url
     FROM challenge_responses cr
     JOIN users u ON u.id = cr.user_id
     WHERE cr.challenge_id = $1 AND cr.response_type != 'skip'
     ORDER BY cr.responded_at ASC`,
    [id]
  );

  // Fetch reactions for all responses
  const responseIds = responses.rows.map((r: any) => r.id);
  let reactionsMap: Record<string, { emoji: string; count: number }[]> = {};

  if (responseIds.length > 0) {
    const reactions = await query(
      `SELECT r.response_id, r.emoji, COUNT(*)::int as count
       FROM reactions r
       WHERE r.response_id = ANY($1)
       GROUP BY r.response_id, r.emoji
       ORDER BY count DESC`,
      [responseIds]
    );

    for (const row of reactions.rows) {
      if (!reactionsMap[row.response_id]) {
        reactionsMap[row.response_id] = [];
      }
      reactionsMap[row.response_id].push({
        emoji: row.emoji,
        count: row.count,
      });
    }
  }

  // Total members in group
  const totalMembersResult = await query(
    `SELECT COUNT(*)::int as count FROM group_members WHERE group_id = $1`,
    [c.group_id]
  );
  const totalMembers = totalMembersResult.rows[0].count;

  // Check if all members have responded
  const totalResponsesResult = await query(
    `SELECT COUNT(*)::int as count FROM challenge_responses WHERE challenge_id = $1`,
    [id]
  );
  const allResponded = totalResponsesResult.rows[0].count >= totalMembers;

  // AI Commentary — check cached value first, generate if missing
  let aiCommentary: string | null = c.ai_commentary || null;
  if (!aiCommentary && responses.rows.length > 0) {
    try {
      const personality: AiPersonality = c.ai_personality || 'funny';
      const responsesData = responses.rows.map((r: any) => ({
        userName: r.display_name || 'Someone',
        answerText: r.answer_text || undefined,
        responseTimeMs: r.response_time_ms || undefined,
      }));
      const commentary = await commentOnResponses(responsesData, personality);
      aiCommentary = commentary.commentary;

      // Cache the commentary on the challenge row
      await query(
        `UPDATE challenges SET ai_commentary = $1 WHERE id = $2`,
        [aiCommentary, id]
      );
    } catch (err: any) {
      logger.error('AI commentary generation failed in reveal', { error: err.message, challengeId: id });
    }
  }

  // Format response
  const formattedResponses = responses.rows.map((r: any) => ({
    id: r.id,
    userId: r.user_id,
    displayName: r.display_name,
    avatarUrl: r.avatar_url,
    photoUrl: r.photo_url,
    answerIndex: r.answer_index,
    answerText: r.answer_text,
    responseTimeMs: r.response_time_ms,
    respondedAt: r.responded_at,
    reactions: reactionsMap[r.id] || [],
  }));

  res.json({
    challenge: {
      id: c.id,
      type: c.type,
      prompt: c.prompt_text,
      groupName: c.group_name,
      groupEmoji: c.group_emoji,
      personality: c.ai_personality || 'funny',
      isAutoGenerated: c.is_auto_generated || false,
    },
    responses: formattedResponses,
    aiCommentary,
    totalMembers,
    allResponded,
  });
}));

// ── GET challenge history ──
router.get('/groups/:groupId/challenges/history', validateUuidParams('groupId'), asyncHandler(async (req: AuthRequest, res: Response) => {
  const groupId = req.params.groupId as string;

  const membership = await query(
    `SELECT * FROM group_members WHERE group_id = $1 AND user_id = $2`,
    [groupId, req.userId]
  );
  if (membership.rows.length === 0) {
    res.status(403).json({ error: 'Not a member of this group' });
    return;
  }

  const limit = Math.min(parseInt(req.query.limit as string) || 20, 100);
  const result = await query(
    `SELECT c.id, c.group_id, c.type,
       c.prompt_text as prompt,
       c.options_json as options,
       c.triggered_by as created_by,
       c.triggered_at as created_at,
       c.expires_at, c.status, c.countdown_seconds,
       (SELECT COUNT(*) FROM challenge_responses WHERE challenge_id = c.id AND response_type != 'skip') as response_count,
       (SELECT COUNT(*)::int FROM group_members WHERE group_id = c.group_id) as member_count,
       EXISTS(SELECT 1 FROM challenge_responses WHERE challenge_id = c.id AND user_id = $2 AND response_type != 'skip') as user_responded,
       (SELECT cr.photo_url FROM challenge_responses cr WHERE cr.challenge_id = c.id AND cr.photo_url IS NOT NULL LIMIT 1) as photo_url
     FROM challenges c
     WHERE c.group_id = $1 AND c.status IN ('completed', 'expired')
     ORDER BY c.triggered_at DESC
     LIMIT $3`,
    [groupId, req.userId, limit]
  );

  // Parse options strings into arrays
  for (const row of result.rows) {
    if (row.options && typeof row.options === 'string') {
      try { row.options = JSON.parse(row.options); } catch { /* keep as-is */ }
    }
  }

  res.json(result.rows);
}));

// ── GET group photo timeline ──
router.get('/groups/:groupId/photos', validateUuidParams('groupId'), asyncHandler(async (req: AuthRequest, res: Response) => {
  const groupId = req.params.groupId as string;
  const limit = Math.min(parseInt(req.query.limit as string) || 30, 100);

  const membership = await query(
    `SELECT 1 FROM group_members WHERE group_id = $1 AND user_id = $2`,
    [groupId, req.userId]
  );
  if (membership.rows.length === 0) {
    res.status(403).json({ error: 'Not a member of this group' });
    return;
  }

  const result = await query(
    `SELECT cr.id, cr.challenge_id, cr.photo_url, cr.responded_at,
       c.prompt_text as prompt, c.type as challenge_type,
       COALESCE(u.display_name, u.phone_number) AS display_name, u.avatar_url
     FROM challenge_responses cr
     JOIN challenges c ON c.id = cr.challenge_id
     JOIN users u ON u.id = cr.user_id
     WHERE c.group_id = $1 AND cr.photo_url IS NOT NULL
     ORDER BY cr.responded_at DESC
     LIMIT $2`,
    [groupId, limit]
  );

  res.json(result.rows);
}));

// ── GET /api/challenges/:id/progress — Who responded (no can't-peek gate) ──
router.get('/:id/progress', validateUuidParams('id'), asyncHandler(async (req: AuthRequest, res: Response) => {
  const id = req.params.id as string;

  // Verify challenge exists
  const challenge = await query(`SELECT group_id FROM challenges WHERE id = $1`, [id]);
  if (challenge.rows.length === 0) {
    res.status(404).json({ error: 'Challenge not found' });
    return;
  }
  const groupId = challenge.rows[0].group_id;

  // Verify user is a group member
  const membership = await query(
    `SELECT * FROM group_members WHERE group_id = $1 AND user_id = $2`,
    [groupId, req.userId]
  );
  if (membership.rows.length === 0) {
    res.status(403).json({ error: 'Not a member of this group' });
    return;
  }

  // Get all group members
  const allMembers = await query(
    `SELECT gm.user_id, COALESCE(u.display_name, u.phone_number) AS display_name, u.avatar_url
     FROM group_members gm
     JOIN users u ON u.id = gm.user_id
     WHERE gm.group_id = $1`,
    [groupId]
  );

  // Get who responded (non-skip)
  const responded = await query(
    `SELECT cr.user_id, COALESCE(u.display_name, u.phone_number) AS display_name, u.avatar_url
     FROM challenge_responses cr
     JOIN users u ON u.id = cr.user_id
     WHERE cr.challenge_id = $1 AND cr.response_type != 'skip'`,
    [id]
  );
  const respondedIds = new Set(responded.rows.map((r: any) => r.user_id));

  const pendingUsers = allMembers.rows
    .filter((m: any) => !respondedIds.has(m.user_id))
    .map((m: any) => ({ userId: m.user_id, displayName: m.display_name, avatarUrl: m.avatar_url }));

  res.json({
    challengeId: id,
    respondedCount: responded.rows.length,
    totalMembers: allMembers.rows.length,
    respondedUsers: responded.rows.map((r: any) => ({
      userId: r.user_id,
      displayName: r.display_name,
      avatarUrl: r.avatar_url,
    })),
    pendingUsers,
  });
}));

// ── GET /api/challenges/:id/preview — Tease data without content ──
router.get('/:id/preview', validateUuidParams('id'), asyncHandler(async (req: AuthRequest, res: Response) => {
  const id = req.params.id as string;

  // Verify challenge exists
  const challenge = await query(`SELECT group_id FROM challenges WHERE id = $1`, [id]);
  if (challenge.rows.length === 0) {
    res.status(404).json({ error: 'Challenge not found' });
    return;
  }
  const groupId = challenge.rows[0].group_id;

  // Verify user is a group member
  const membership = await query(
    `SELECT * FROM group_members WHERE group_id = $1 AND user_id = $2`,
    [groupId, req.userId]
  );
  if (membership.rows.length === 0) {
    res.status(403).json({ error: 'Not a member of this group' });
    return;
  }

  // Total members
  const totalMembersResult = await query(
    `SELECT COUNT(*)::int as count FROM group_members WHERE group_id = $1`,
    [groupId]
  );
  const totalMembers = totalMembersResult.rows[0].count;

  // Who responded (non-skip)
  const responded = await query(
    `SELECT cr.user_id, COALESCE(u.display_name, u.phone_number) AS display_name, u.avatar_url
     FROM challenge_responses cr
     JOIN users u ON u.id = cr.user_id
     WHERE cr.challenge_id = $1 AND cr.response_type != 'skip'`,
    [id]
  );

  // Total reactions across all responses in this challenge
  const reactionsResult = await query(
    `SELECT COUNT(*)::int as total_reactions
     FROM reactions r
     JOIN challenge_responses cr ON cr.id = r.response_id
     WHERE cr.challenge_id = $1`,
    [id]
  );
  const totalReactions = reactionsResult.rows[0]?.total_reactions || 0;

  // Top reaction emoji
  const topEmojiResult = await query(
    `SELECT r.emoji, COUNT(*) as cnt
     FROM reactions r
     JOIN challenge_responses cr ON cr.id = r.response_id
     WHERE cr.challenge_id = $1
     GROUP BY r.emoji
     ORDER BY cnt DESC
     LIMIT 1`,
    [id]
  );
  const topReactionEmoji = topEmojiResult.rows[0]?.emoji || null;

  res.json({
    challengeId: id,
    respondedCount: responded.rows.length,
    totalMembers,
    totalReactions,
    topReactionEmoji,
    respondedUsers: responded.rows.map((r: any) => ({
      userId: r.user_id,
      displayName: r.display_name,
      avatarUrl: r.avatar_url,
    })),
  });
}));

export default router;
