import React, { useEffect, useRef } from 'react';
import { View, Text, StyleSheet, Animated } from 'react-native';
import { theme } from '@/constants/colors';

interface BlinkAiAvatarProps {
  size?: number;
}

/**
 * A small circular avatar representing "Blink AI" — used when a challenge
 * has `triggered_by = null`, meaning it was auto-generated by the AI scheduler.
 * Shows a sparkle emoji inside a coral circle with a subtle shimmer badge.
 */
export default function BlinkAiAvatar({ size = 28 }: BlinkAiAvatarProps) {
  const shimmerAnim = useRef(new Animated.Value(0)).current;

  useEffect(() => {
    Animated.loop(
      Animated.sequence([
        Animated.timing(shimmerAnim, {
          toValue: 1,
          duration: 1500,
          useNativeDriver: true,
        }),
        Animated.timing(shimmerAnim, {
          toValue: 0,
          duration: 1500,
          useNativeDriver: true,
        }),
      ])
    ).start();
  }, [shimmerAnim]);

  const shimmerOpacity = shimmerAnim.interpolate({
    inputRange: [0, 1],
    outputRange: [0.5, 1],
  });

  return (
    <View style={[styles.container, { width: size, height: size, borderRadius: size / 2 }]}>
      <Text style={[styles.emoji, { fontSize: size * 0.5 }]}>{'\u2728'}</Text>
      <Animated.View
        style={[
          styles.shimmerBadge,
          {
            opacity: shimmerOpacity,
            right: -2,
            bottom: -2,
            width: size * 0.4,
            height: size * 0.4,
            borderRadius: (size * 0.4) / 2,
          },
        ]}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    backgroundColor: theme.coral,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  emoji: {
    textAlign: 'center',
  },
  shimmerBadge: {
    position: 'absolute',
    backgroundColor: theme.purple,
    borderWidth: 1.5,
    borderColor: theme.bg,
  },
});
